### PR TITLE
Add pretty-printing reporter.

### PR DESCRIPTION
**Pull request by mikeybtn**
Adds a new formatter (default disabled) which attempts to produce a more readable output.

Example showing both the existing behavior and the new:
image

### CODE REVIEW

**Comment by ebdrup** [comment]
Thanks a lot for the pull request. Readable output is important.

I'm wondering if this output formatting does not belong in the jshint module instead? What do you think?

**Comment by mikeybtn** [comment]
Thanks for the module! We use it a lot.

> I'm wondering if this output formatting does not belong in the jshint module instead? What do you think?

Something similar might make sense there! In this case where we're getting structured results back from jshint, it feels like `mocha-jshint` is a different type for "frontend" for the library, and so naturally owns how to present the results. (In that sense I contemplated simply replacing the built-in `reporter.js` rather than making it an option.)

**Comment by mikeybtn** [comment]
@ebdrup did you have a preference? Just trying to determine whether I'll be maintaining this locally. thanks again!

**Comment by ebdrup** [comment]
I can merge it if you like. My only concern is that the code makes a lot of assumptions about how jshint outputs. And thus might break easily. I think if this was implemented at the source in jshint the code would me much simpler and wouldn't break as easily.

Do you want to give it a shot as a PR to jshint? Or do you just want me to merge it?

**Comment by ebdrup** [comment]
Oh, and I will not be using this myself, so it's good that it is an option. The current output is made the way it is intentionally because webstorm turns that aoutput into clickable links that take you directly to the place in the source code that has the error.

**Comment by mikeybtn** [comment]
> My only concern is that the code makes a lot of assumptions about how jshint outputs.

Can you point at where those are? The reporter builds its output from fields in the jshint `results` structure, precisely the same as the existing reporter uses, so I don't see how it would be any more brittle. There is no other dependency on jshint.

**Comment by ebdrup** [comment]
Sorry that's me. Didn't read the code properly. I just skimmed it and made assumptions because it's a bit verbose.

Nevermind I'll merge it. But I think we should rename the option `fancy`-> `pretty`. 
That seems to be the standard (prettyprint). You use the word pretty yourself in the Readme.

Would be nice if there is an also is an example of standard output in the readme :-)

**Comment by ebdrup** [comment]
I would normally do these changes myself, before merging. But I've got to go teach kids programming at http://codingpirates.dk now :-)

**Comment by mikeybtn** [comment]
> Nevermind I'll merge it. But I think we should rename the option fancy-> pretty. 
> That seems to be the standard (prettyprint). You use the word pretty yourself in the Readme.

No problem, done!

> I would normally do these changes myself, before merging. But I've got to go teach kids programming at http://codingpirates.dk now :-)

Hey, that's pretty cool! A well-worthy pursuit.

I tacked on a version bump, assuming it could save you some time -- happy to pull that out if it was the wrong assumption. Thanks again!

cheers,
mikey

**Comment by ebdrup** [comment]
I normally do version bumps myself with npm. That also adds a tag :-)
(In the bus, I'll merge tonight or tomorrow)

**Comment by mikeybtn** [comment]
No problem - reverted the bump!

**Pull request merged**
